server:
  port: 8090

spring:
  cache:
    type: redis
    redis:
      database: SheetNotesDb
      host: localhost
      port: 6379
      timeout: 60000
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SheetNotesDb
    username: root
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

api:
  url: /api/v1
  auth:
    url: http://localhost:8091/api/auth

logging:
  file:
    name: /home/alex/wrtn.log
  logback:
    rollingpolicy:
      max-history: 2
      max-file-size: 10MB
  level:
    root: info
    org:
    springframework: info
